Repository WildCodeSchool/202302-orleans-php-project2-jeanetteverdier, pull requests merged in 2023-04, with the labels that each got.

#2 Init
  public/assets/css/style.css
  src/View/layout.html.twig
Labels: REVIEWED, CORRECTIONS DONE

#4 S02 us01 navbar
  .DS_Store
  .gitignore
  database.sql
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/login.png
  public/assets/images/logo-school.jpeg
  public/assets/javascript/navbar.js
  src/.DS_Store
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: CHANGES REQUESTED, REVIEWED

#5 Ajustement des clamps et modification de les liste de la navbar
  .DS_Store
  public/assets/css/navbar.css
  public/assets/css/style.css
  src/.DS_Store
  src/View/Components/_navbar.html.twig
Labels: REVIEWED

#7 Push dev to main navbar
  .DS_Store
  .gitignore
  database.sql
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/login.png
  public/assets/images/logo-school.jpeg
  public/assets/javascript/navbar.js
  src/.DS_Store
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#8 creation footer
  .DS_Store
  public/assets/css/footer.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/adress.png
  public/assets/images/location.png
  public/assets/images/logo-academie.png
  public/assets/images/logo-centre.png
  public/assets/images/mail.png
  public/assets/images/phone.png
  public/assets/images/website.png
  src/View/Components/_footer.html.twig
  src/View/layout.html.twig
Labels: CHANGES REQUESTED, REVIEWED

#9 la page qui affiche l'équipe
  database.sql
  public/assets/css/style.css
  public/assets/css/team.css
  public/assets/images/professeursPhotos/teacherByDefault.jpg
  src/Controller/EmployeeController.php
  src/Model/EmployeeManager.php
  src/Model/WorkDepartementsManager.php
  src/View/Pages/employee.html.twig
  src/routes.php
Labels: REVIEWED

#10 creation de l'index des formations
  .DS_Store
  database.sql
  public/assets/css/footer.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/css/training.css
  public/assets/images/placeholder.jpg
  src/.DS_Store
  src/Controller/TrainingController.php
  src/Model/TrainingManager.php
  src/View/Components/_navbar.html.twig
  src/View/Training/index.html.twig
  src/routes.php
Labels: REVIEWED

#11 creation des tables sector et affichage des secteurs via leurs secteurs
  database.sql
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/css/training.css
  src/Controller/TrainingController.php
  src/Model/SectorManager.php
  src/Model/TrainingManager.php
  src/View/Training/index.html.twig
Labels: REVIEWED

#12 fixe training manager
  src/Model/TrainingManager.php
Labels: REVIEWED

#15 fixe css
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/css/team.css
Labels: REVIEWED

#17 dev to main
  .DS_Store
  database.sql
  public/assets/css/contactForm.css
  public/assets/css/footer.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/css/team.css
  public/assets/css/training.css
  public/assets/images/adress.png
  public/assets/images/location.png
  public/assets/images/logo-academie.png
  public/assets/images/logo-centre.png
  public/assets/images/mail.png
  public/assets/images/phone.png
  public/assets/images/placeholder.jpg
  public/assets/images/professeursPhotos/teacherByDefault.jpg
  public/assets/images/website.png
  src/.DS_Store
  src/Controller/ContactController.php
  src/Controller/EmployeeController.php
  src/Controller/TrainingController.php
  src/Model/DegreeManager.php
  src/Model/EmployeeManager.php
  src/Model/SectorManager.php
  src/Model/TrainingManager.php
  src/Model/WorkDepartementsManager.php
  src/View/Components/_footer.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Contact/contactForm.html.twig
  src/View/Home/index.html.twig
  src/View/Pages/employee.html.twig
  src/View/Training/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED
